[build]
functions = "netlify/functions"

[[redirects]]
from = "/bro-price"
to = "/.netlify/functions/bro-price"
status = 200

[[redirects]]
from = "/alph-price"
to = "/.netlify/functions/alph-price"
status = 200
